services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADDRESS:  "0.0.0.0:8080"
      DATABASE_DSN: "postgres://postgres:postgres@postgres:5432/metrics?sslmode=disable"
    ports:
      - "8080:8080"
    command: ["/server"]

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    depends_on:
      server:
        condition: service_started
    environment:
      ADDRESS:  "server:8080"
    command: ["/agent"]