name: tests

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  unittests:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          go test ./... -v